async function main() {
  console.log(":0");
}

main().catch((err) => {
  console.log(err);
  process.exit(1);
});
